apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "service" }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: express-port
      protocol: TCP
      name: express-port
  selector:
    app: {{.Release.Name}}
